services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: luna
      POSTGRES_PASSWORD: luna
      POSTGRES_DB: luna_development
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
