app = "luna-api-kkwondev"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:migrate"

[env]
  HTTP_PORT = "8080"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_SERVE_STATIC_FILES = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0  # MVP 단계에서 비용 절감 목적. 실서비스 전환 시 1로 변경 권장
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
